###
#---------------------- users ----------------------
GET http://localhost:9080/plant_manager/api/users
###
// @no-cookie-jar
PUT http://localhost:9080/plant_manager/api/users/9b988872-e8fb-49d7-9152-10e4cfde6776
Content-Type: application/json

{
  "name": "lepin3",
  "login": "lepin3",
  "password": "lepinlepin"
}


###
#---------------------- species ----------------------
# all species

// @no-cookie-jar
GET http://localhost:9080/plant_manager/api/species
Authorization: Basic bGVwaW4zOmxlcGlubGVwaW4=
//Authorization: Basic a2V2aW46dXNlcnVzZXI= //useruser kevin
//Authorization: Basic YWRtaW46YWRtaW5hZG1pbg== //adminadmin
###
# existing species

// @no-cookie-jar
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
###

// @no-cookie-jar
DELETE http://localhost:9080/plant_manager/api/species/a07d4383-284f-490d-9817-cc4c362d5f59
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
###
# non exitsitn species 404
// @no-cookie-jar
GET http://localhost:9080/plant_manager/api/species/9b988872-e8fb-49d7-9152-10e4cfde6886

###
# create new species
// @no-cookie-jar
PUT http://localhost:9080/plant_manager/api/species/9b988872-e8fb-49d7-9152-10e4cfde6886
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

{
  "lightType": "MEDIUM",
  "fullName": "Default full name",
  "commonName": "Default common name",
  "family": "family",
  "description": "lorem ipsum",
  "wateringRateInDays": 24,
  "origin": "europa"
}

###
# update species.
// @no-cookie-jar
PATCH http://localhost:9080/plant_manager/api/species/9b988872-e8fb-49d7-9152-10e4cfde6886
Content-Type: application/json

{
  "fullName": "Changed full name",
  "commonName": "Changed common name",
  "description": "Changed lorem ipsum"
}

###
#---------------------- plants ----------------------
// @no-cookie-jar
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants
Authorization: Basic a2V2aW46dXNlcnVzZXI=
//Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==
###
# get plants from non existing species
// @no-cookie-jar
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f455/plants
Authorization: Basic a2V2aW46dXNlcnVzZXI=
###
# get exising plant
// @no-cookie-jar
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/2dfa8535-39af-4fbb-9995-0e8340710f04
//Authorization: Basic a2V2aW46dXNlcnVzZXI=
//Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

###
// @no-cookie-jar
DELETE http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c117517e
Authorization: Basic a2V2aW46dXNlcnVzZXI=
//Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

###
# get non exising plant fomr exisitng species
// @no-cookie-jar
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c1175177

###
# create new plant
PUT http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c1175178
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW5hZG1pbg==

{
  "name": "Default name22",
  "description": "lorem ipsum",
  "age": 24
}

###
# update plant
PATCH http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c1175177
Content-Type: application/json

{
  "name": "Changed full name",
  "description": "Changed lorem ipsum",
  "age": 0
}

###
