#---------------------- users ----------------------
GET http://localhost:9080/plant_manager/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00aa

###
GET http://localhost:9080/plant_manager/api/users

###

GET http://localhost:9080/plant_manager/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6

###

GET http://localhost:9080/plant_manager/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar

###

GET http://localhost:9080/plant_manager/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00aa/avatar

###

DELETE http://localhost:9080/plant_manager/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar

###

DELETE http://localhost:9080/plant_manager/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00aa/avatar

###

PUT http://localhost:9080/plant_manager/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="sigrid.png"

< C:\\Users\\groch\\Desktop\\jee\\plant_manager\\test_avatars\\sigrid.png
--boundary--

###

PATCH http://localhost:9080/plant_manager/api/users/c4804e0f-769e-4ab9-9ebe-0578fb4f00a6/avatar
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="calvian.png"
Content-Type: image/png

< C:/Users/groch/Desktop/jee/plant_manager/test_avatars/calvian.png
--boundary--

###
#---------------------- species ----------------------
# all species
GET http://localhost:9080/plant_manager/api/species

###
# existing species
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c

###

DELETE http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c

###
# non exitsitn species 404
GET http://localhost:9080/plant_manager/api/species/9b988872-e8fb-49d7-9152-10e4cfde6886

###
# create new species
PUT http://localhost:9080/plant_manager/api/species/9b988872-e8fb-49d7-9152-10e4cfde6886
Content-Type: application/json

{
  "lightType": "MEDIUM",
  "fullName": "Default full name",
  "commonName": "Default common name",
  "family": "family",
  "description": "lorem ipsum",
  "wateringRateInDays": 24,
  "origin": "europa"
}

###
# update species.
PATCH http://localhost:9080/plant_manager/api/species/9b988872-e8fb-49d7-9152-10e4cfde6886
Content-Type: application/json

{
  "fullName": "Changed full name",
  "commonName": "Changed common name",
  "description": "Changed lorem ipsum"
}

###
#---------------------- plants ----------------------

GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants

###
# get plants from non existing species
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f455/plants

###
# get exising plant
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c117517e

###

DELETE http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c117517e

###
# get non exising plant fomr exisitng species
GET http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c1175177

###
# create new plant
PUT http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c1175177
Content-Type: application/json

{
  "name": "Default name",
  "description": "lorem ipsum",
  "age": 24
}

###
# update plant
PATCH http://localhost:9080/plant_manager/api/species/83da3ba6-c7e4-4dfe-846a-64284677f45c/plants/0b8c0653-b196-4ac4-8015-3e43c1175177
Content-Type: application/json

{
  "name": "Changed full name",
  "description": "Changed lorem ipsum",
  "age": 0
}

###
